=== riezebosch/xsd11/lab01/Solution/auto-loan-application.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" vc:minVersion="1.1">
	<xs:element name="Loan-Application">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Applicant">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Name" type="xs:string"/>
							<xs:element name="Age" type="xs:unsignedByte"/>
							<xs:element name="Address">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Street" type="xs:string"/>
										<xs:element name="City" type="xs:string"/>
										<xs:element name="State">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="CT"/>
													<xs:enumeration value="MA"/>
													<xs:enumeration value="ME"/>
													<xs:enumeration value="NH"/>
													<xs:enumeration value="RI"/>
													<xs:enumeration value="VT"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:assert test="if (Address/State eq 'CT') then number(Age) ge 19 else
                                      if (Address/State eq 'MA') then number(Age) ge 18 else
                                      if (Address/State eq 'ME') then number(Age) ge 19 else
                                      if (Address/State eq 'NH') then number(Age) ge 17 else
                                      if (Address/State eq 'RI') then number(Age) ge 18 else
                                      if (Address/State eq 'VT') then number(Age) ge 16 else
                                      false()"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Car">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Make" type="xs:string"/>
							<xs:element name="Model" type="xs:string"/>
							<xs:element name="Year" type="xs:gYear"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Loan-Amount" type="xs:unsignedInt"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== riezebosch/xsd11/lab01/auto-loan-application.xml
<?xml version="1.0"?>
<Loan-Application xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/XSD11/Labs/lab01/auto-loan-application.xsd">
	<Applicant>
		<Name>Johnny Brown</Name>
		<Age>17</Age>
		<Address>
			<Street>101 Curl Drive</Street>
			<City>Burlington</City>
			<State>VT</State>
		</Address>
	</Applicant>
	<Car>
		<Make>Mazda</Make>
		<Model>Miata</Model>
		<Year>2009</Year>
	</Car>
	<Loan-Amount>26000</Loan-Amount>
</Loan-Application>
